package me.codeenzyme.reminder

const val ALARM_TITLE = "ALARM_TITLE"
const val ALARM_MESSAGE = "ALARM MESSAGE"

const val ALARM_ACTION = "ALARM_ACTION"

const val ALARM_INTERVAL = "ALARM_INTERVAL"

const val ALARM_CURRENT_RING_TIME = "ALARM_CURRENT_RING_TIME"